### ISSUE TITLE
Publish linux release for 1.1?

### ISSUE THREAD

**Issue by cahna** [univrsal/dvds3#1]
Thanks for this plugin <3

May I request an updated release to include the latest linux build? [The latest release](https://github.com/univrsal/dvds3/releases/tag/v1.1) doesn't have the `.so` file for linux. [`v1.0`](https://github.com/univrsal/dvds3/releases/tag/1.0) works for me on Manjaro, but I cannot get the latest source code to build (I tried to build using steps similar to [these for obs-v4l2loopback](https://github.com/CatxFish/obs-v4l2sink#build)).

Or if you could provide build instructions, I will create a PR to add a [github workflow](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow) to automatically build+release for linux.

**Comment by univrsal** [comment]
Can you checkout [independent-build](https://github.com/univrsal/dvds3/tree/independent-build)? Building for linux should then just be the following commands
```
$ git clone https://github.com/univrsal/dvds3.git
$ cd dvds3
$ git checkout independent-build
$ mkdir build && cd build
$ cmake ..
$ make && make install
```
This will install the plugin for the current user. I didn't go for a global installation since the destination folder for that seems to differ for each distro and it requires sudo/root.

**Comment by cahna** [comment]
Thank you! That worked, and I appreciate the user-level install :)
